const {app,BrowserWindow,ipcMain,dialog,Menu,shell}=require('electron');
const path=require('path'),fs=require('fs'),Database=require('better-sqlite3');
const {calc,MATERIALS,COEFFICIENTS}=require('./engine');
const ExcelJS=require('exceljs'),PDFDocument=require('pdfkit');
const license=require('./license'); // Sistem lisensi RAB Rumahku Pro — trial 7 hari, lisensi tahunan (© UNA Digital Solution)
let db,win;
function createDB(){const dir=app.getPath('userData');fs.mkdirSync(dir,{recursive:true});db=new Database(path.join(dir,'rab-rumahku.db'));db.pragma('journal_mode = WAL');db.exec('CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY,data TEXT NOT NULL,updated_at TEXT NOT NULL)');}
function create(){win=new BrowserWindow({width:1500,height:950,minWidth:1100,minHeight:700,autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:false}});win.loadFile(path.join(__dirname,'index.html'));}
function data(){return require(path.join(__dirname,'../../shared/data.json'));}
app.whenReady().then(()=>{Menu.setApplicationMenu(null);createDB();create();
 win.webContents.once('did-finish-load',async()=>{try{const st=await license.getLicenseStatus();win.webContents.send('license:init',st);}catch(e){console.error('[license] gagal cek status:',e.message);}});
});
ipcMain.handle('license:status',()=>license.getLicenseStatus());
ipcMain.handle('license:activate',(_,key)=>license.activateLicense(key));
ipcMain.handle('license:openPurchase',()=>{shell.openExternal('https://simtrenpro.web.app/lisensi.html?produk=rab');return true;});
app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});
ipcMain.handle('getData',()=>data());
ipcMain.handle('getMaterials',()=>MATERIALS); ipcMain.handle('getCoefficients',()=>COEFFICIENTS);
ipcMain.handle('list',()=>db.prepare('SELECT id,data,updated_at FROM projects ORDER BY updated_at DESC').all().map(x=>({...JSON.parse(x.data),id:x.id,updatedAt:x.updated_at})));
ipcMain.handle('save',(_,p)=>{const now=new Date().toISOString();db.prepare('INSERT OR REPLACE INTO projects(id,data,updated_at) VALUES(?,?,?)').run(p.id,JSON.stringify(p),now);return true;});
ipcMain.handle('deleteProject',(_,id)=>{db.prepare('DELETE FROM projects WHERE id=?').run(id);return true;});
ipcMain.handle('calc',(_,p)=>calc(p));
ipcMain.handle('exportExcel',async(_,payload)=>{const {filePath}=await dialog.showSaveDialog(win,{defaultPath:'RAB-Rumahku.xlsx',filters:[{name:'Excel',extensions:['xlsx']}]});if(!filePath)return null;const wb=new ExcelJS.Workbook();wb.creator='RAB Rumahku';
 const ws=wb.addWorksheet('RAB Detail');ws.addRow(['RAB RUMAHKU PRO']);ws.addRow(['Proyek',payload.project.name]);ws.addRow(['Pemilik',payload.project.owner]);ws.addRow(['Lokasi',payload.project.location]);ws.addRow(['Luas lantai',payload.result.summary.area]);ws.addRow([]);ws.addRow(['No','Kategori','Uraian','Volume','Satuan','Waste %','Harga Satuan','Jumlah']);payload.result.items.forEach((x,i)=>ws.addRow([i+1,x.category,x.description,x.volume,x.unit,x.waste||0,x.unitPrice,x.amount]));ws.addRow([]);ws.addRow(['','','MATERIAL',payload.result.summary.material]);ws.addRow(['','','TENAGA KERJA',payload.result.summary.labor]);ws.addRow(['','','PERALATAN',payload.result.summary.equipment]);ws.addRow(['','','OVERHEAD',payload.result.summary.overhead]);ws.addRow(['','','CONTINGENCY',payload.result.summary.contingency]);ws.addRow(['','','TRANSPORT',payload.result.summary.transport]);ws.addRow(['','','PROFIT',payload.result.summary.profit]);ws.addRow(['','','TOTAL RAB',payload.result.summary.total]);ws.addRow([]);ws.addRow(['Copyright © 2026 UNA Digital Solution']);
 const wm=wb.addWorksheet('Material');wm.addRow(['Material','ID','Kategori','Teoritis','Pembelian','Satuan','Waste %','Harga Satuan','Nilai']);(payload.result.materialRecap||[]).forEach(m=>wm.addRow([m.materialName,m.materialId,m.category,m.theoreticalQuantity,m.purchaseQuantity,m.unit,(m.sources?.[0]?.waste)||0,m.unitPrice,m.totalCost]));
 const wa=wb.addWorksheet('Asumsi');[['Parameter','Nilai'],['Panjang bangunan',payload.project.building.length],['Lebar bangunan',payload.project.building.width],['Lantai',payload.project.building.floors],['Tinggi dinding',payload.project.building.wallHeight],['Kemiringan atap',payload.project.building.roofPitch],['Overstek',payload.project.building.overhang],['Dinding',payload.result.assumptions.wall],['Lantai',payload.result.assumptions.floor],['Atap',payload.result.assumptions.roof],['Plafon',payload.result.assumptions.ceiling],['Catatan','Harga referensi dan koefisien adalah estimasi; verifikasi lapangan.']].forEach(r=>wa.addRow(r));
 [ws,wm,wa].forEach(s=>{s.getRow(1).font={bold:true,size:14};s.columns.forEach(c=>c.width=Math.min(45,Math.max(12,(c.header||'').length+4)));});await wb.xlsx.writeFile(filePath);return filePath;});
ipcMain.handle('exportPdf',async(_,payload)=>{const {filePath}=await dialog.showSaveDialog(win,{defaultPath:'RAB-Rumahku.pdf',filters:[{name:'PDF',extensions:['pdf']}]});if(!filePath)return null;await new Promise((res,rej)=>{const d=new PDFDocument({margin:42,size:'A4'});d.pipe(fs.createWriteStream(filePath));const m=n=>'Rp'+Math.round(n||0).toLocaleString('id-ID');d.fontSize(22).text('RAB RUMAHKU PRO').fontSize(10).text('Rencana Anggaran Biaya & Quantity Takeoff').moveDown();d.fontSize(12).text(`Proyek: ${payload.project.name||'-'}`).text(`Pemilik: ${payload.project.owner||'-'}`).text(`Lokasi: ${payload.project.location||'-'}`).text(`Bangunan: ${payload.project.building.length} × ${payload.project.building.width} m · ${payload.result.summary.area.toFixed(2)} m²`).moveDown();d.fontSize(14).text(`TOTAL RAB: ${m(payload.result.summary.total)}`).fontSize(10).text(`Biaya per m²: ${m(payload.result.summary.costPerM2)}`).moveDown();for(const [cat,items] of Object.entries(payload.result.groups)){d.fontSize(12).text(`${cat} — ${m(items.reduce((a,x)=>a+x.amount,0))}`);d.fontSize(8);items.forEach((x,i)=>d.text(`${i+1}. ${x.description} | ${x.volume.toFixed(2)} ${x.unit} | ${m(x.unitPrice)} | ${m(x.amount)}`));d.moveDown(0.3);}d.fontSize(10).moveDown().text(`Material: ${m(payload.result.summary.material)}   Tenaga: ${m(payload.result.summary.labor)}   Peralatan: ${m(payload.result.summary.equipment)}`).text(`Overhead: ${m(payload.result.summary.overhead)}   Contingency: ${m(payload.result.summary.contingency)}   Transport: ${m(payload.result.summary.transport)}`);d.moveDown().fontSize(12).text('REKAP MATERIAL').fontSize(8);for(const item of (payload.result.materialRecap||[])){d.text(`${item.materialName} | Teoritis ${item.theoreticalQuantity.toFixed(2)} ${item.unit} | Pembelian ${item.purchaseQuantity.toFixed(2)} ${item.unit} | ${item.category} | ${m(item.totalCost)}`);}d.moveDown();d.moveDown().fontSize(8).text('Catatan: estimasi berbasis parameter proyek, asumsi konstruksi, dan harga referensi. Verifikasi gambar kerja, kondisi tanah, metode pelaksanaan, spesifikasi, dan harga supplier sebelum pembangunan.');d.moveDown().fontSize(7).fillColor('#94a3b8').text('Copyright © 2026 UNA Digital Solution — RAB Rumahku Pro',{align:'center'});d.end();d.on('finish',res);d.on('error',rej);});return filePath;});
ipcMain.handle('importProject',async()=>{const r=await dialog.showOpenDialog(win,{properties:['openFile'],filters:[{name:'RAB Rumahku',extensions:['rabrumah','json']}]});if(r.canceled)return null;return JSON.parse(fs.readFileSync(r.filePaths[0],'utf8'));});
ipcMain.handle('exportProject',async(_,p)=>{const r=await dialog.showSaveDialog(win,{defaultPath:(p.name||'proyek')+'.rabrumah',filters:[{name:'RAB Rumahku',extensions:['rabrumah']}]});if(r.canceled)return null;fs.writeFileSync(r.filePath,JSON.stringify(p,null,2));return r.filePath;});
