import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'rab_engine.dart';

typedef JsonMap = Map<String,dynamic>;
String money(num v) => 'Rp ${NumberFormat('#,##0', 'id_ID').format(v.round())}';
void main() => runApp(const RabRumahApp());
class RabRumahApp extends StatefulWidget { const RabRumahApp({super.key}); @override State<RabRumahApp> createState()=>_AppState(); }
class RabApp extends RabRumahApp { const RabApp({super.key}); }
class _AppState extends State<RabRumahApp> {
  int page=0; JsonMap profile={'name':'RAB Rumahku','logo':'','address':'','contact':''}; List<JsonMap> projects=[]; List<JsonMap> customMaterials=[];
  @override void initState(){super.initState();load();}
  Future<void> load() async { final s=await SharedPreferences.getInstance(); final p=s.getString('profile'),r=s.getString('projects'),m=s.getString('materials'); setState((){if(p!=null)profile=JsonMap.from(jsonDecode(p));if(r!=null)projects=List<JsonMap>.from((jsonDecode(r) as List).map((x)=>JsonMap.from(x)));if(m!=null)customMaterials=List<JsonMap>.from((jsonDecode(m) as List).map((x)=>JsonMap.from(x)));}); }
  Future<void> save() async {final s=await SharedPreferences.getInstance();await s.setString('profile',jsonEncode(profile));await s.setString('projects',jsonEncode(projects));await s.setString('materials',jsonEncode(customMaterials));}
  void nav(int i){setState(()=>page=i);}
  @override Widget build(BuildContext c){final pages=[HomePage(profile:profile,projects:projects,onNew:()=>nav(1)),EditorPage(onSave:(p){setState(()=>projects=[p,...projects]);save();nav(2);}),ProjectsPage(projects:projects,onDelete:(i){setState(()=>projects.removeAt(i));save();},onNew:()=>nav(1)),MaterialPageX(items:customMaterials,onChanged:(x){setState(()=>customMaterials=x);save();}),MorePage(onNav:nav),ReportPage(projects:projects,profile:profile),SettingsPage(profile:profile,onSave:(x){setState(()=>profile=x);save();}),const CalculatorPage(),const ReceiptPage()]; return MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:Scaffold(appBar:AppBar(title:Text('${profile['name']??'RAB Rumahku'}'),actions:[IconButton(icon:const Icon(Icons.calculate_outlined),onPressed:()=>nav(7)),IconButton(icon:const Icon(Icons.receipt_long_outlined),onPressed:()=>nav(8))]),drawer:AppDrawer(page:page,onNav:nav),body:pages[page],bottomNavigationBar:NavigationBar(selectedIndex:page<5?page:4,onDestinationSelected:nav,destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),label:'Beranda'),NavigationDestination(icon:Icon(Icons.add_box_outlined),label:'Buat RAB'),NavigationDestination(icon:Icon(Icons.folder_outlined),label:'Proyek'),NavigationDestination(icon:Icon(Icons.inventory_2_outlined),label:'Material'),NavigationDestination(icon:Icon(Icons.more_horiz),label:'Lainnya')])));}
}
class AppDrawer extends StatelessWidget {final int page;final ValueChanged<int> onNav;const AppDrawer({super.key,required this.page,required this.onNav});@override Widget build(BuildContext c)=>Drawer(child:ListView(children:[const DrawerHeader(child:Center(child:Text('RAB RUMAHKU',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)))),...[(0,'Beranda',Icons.home),(1,'Buat RAB',Icons.add_box),(2,'Proyek Saya',Icons.folder),(3,'Material',Icons.inventory_2),(4,'Galeri',Icons.image),(5,'Laporan',Icons.assessment),(6,'Pengaturan',Icons.settings),(7,'Kalkulator',Icons.calculate),(8,'Kwitansi',Icons.receipt_long)].map((x)=>ListTile(selected:page==x.$1,leading:Icon(x.$3),title:Text(x.$2),onTap:(){Navigator.pop(c);onNav(x.$1);})),const Padding(padding:EdgeInsets.all(16),child:Text('Offline-first • SPK mobile'))]));}
class HomePage extends StatelessWidget {final JsonMap profile;final List<JsonMap> projects;final VoidCallback onNew;const HomePage({super.key,required this.profile,required this.projects,required this.onNew});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('PERENCANAAN RUMAH',style:Theme.of(c).textTheme.labelLarge),Text('Denah → Material → RAB → Maket',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:10),Text('Semua data proyek disimpan lokal di perangkat.'),const SizedBox(height:16),FilledButton.icon(onPressed:onNew,icon:const Icon(Icons.add),label:const Text('BUAT RAB BARU'))])),const SizedBox(height:12),Row(children:[Expanded(child:StatCard('Proyek','${projects.length}',Icons.folder)),Expanded(child:StatCard('RAB','${projects.length}',Icons.receipt_long))]),const SizedBox(height:12),Text('Identitas',style:Theme.of(c).textTheme.titleLarge),ListTile(leading:const Icon(Icons.business),title:Text(profile['name']??'-'),subtitle:Text(profile['address']??'')),const Divider(),Text('Proyek terbaru',style:Theme.of(c).textTheme.titleLarge),if(projects.isEmpty)const ListTile(title:Text('Belum ada proyek'))else...projects.take(5).map((p)=>Card(child:ListTile(title:Text(p['name']??'-'),subtitle:Text('${p['length']??0} × ${p['width']??0} m'),trailing:Text(money(p['total']??0)))))]);}
class StatCard extends StatelessWidget{final String a,b;final IconData icon;const StatCard(this.a,this.b,this.icon,{super.key});@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(children:[Icon(icon),Text(b,style:const TextStyle(fontWeight:FontWeight.bold)),Text(a)])));}
class EditorPage extends StatefulWidget{final ValueChanged<JsonMap> onSave;const EditorPage({super.key,required this.onSave});@override State<EditorPage> createState()=>_EditorState();}
class _EditorState extends State<EditorPage>{final name=TextEditingController(text:'Rumah Baru'),owner=TextEditingController(),location=TextEditingController();double length=6,width=6,height=3,overhang=.5;int floors=1,doors=4,windows=5,bathrooms=1;String wall='lightbrick',floor='tile',roof='genteng',ceiling='gypsum';bool top=true;int tab=0;@override void dispose(){name.dispose();owner.dispose();location.dispose();super.dispose();}
 JsonMap input()=>{'building':{'length':length,'width':width,'wallHeight':height,'floors':floors,'overhang':overhang,'roofPitch':30,'bathrooms':bathrooms,'openings':{'doors':doors,'windows':windows}},'spec':{'wall':wall,'floor':floor,'roofCover':roof,'ceiling':ceiling}};
 void finish(){final r=RabEngine.calculate(input());onSave({'name':name.text.isEmpty?'Rumah Baru':name.text,'owner':owner.text,'location':location.text,'length':length,'width':width,'floors':floors,'area':r['geometry']['floorArea'],'total':r['summary']['total'],'rab':r,'createdAt':DateTime.now().toIso8601String()});}
 Widget numBox(String l,double v,ValueChanged<double> f)=>TextFormField(initialValue:'$v',keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:l,border:const OutlineInputBorder()),onChanged:(x)=>f(double.tryParse(x)??v));
 Widget select(String l,String v,List<String> items,ValueChanged<String> f)=>Padding(padding:const EdgeInsets.only(bottom:10),child:DropdownButtonFormField<String>(value:v,decoration:InputDecoration(labelText:l,border:const OutlineInputBorder()),items:items.map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x){if(x!=null)f(x);}));
 @override Widget build(BuildContext c){final r=RabEngine.calculate(input());final s=JsonMap.from(r['summary']);return ListView(padding:const EdgeInsets.all(16),children:[Text('Buat RAB',style:Theme.of(c).textTheme.headlineSmall),const SizedBox(height:12),Wrap(spacing:6,children:['Data','Dimensi','Spesifikasi','RAB','Maket'].asMap().entries.map((e)=>ChoiceChip(label:Text('${e.key+1}. ${e.value}'),selected:tab==e.key,onSelected:(_){setState(()=>tab=e.key);})).toList()),const SizedBox(height:16),if(tab==0)...[TextField(controller:name,decoration:const InputDecoration(labelText:'Nama proyek',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:owner,decoration:const InputDecoration(labelText:'Pemilik',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:location,decoration:const InputDecoration(labelText:'Lokasi',border:OutlineInputBorder()))]else if(tab==1)...[Row(children:[Expanded(child:numBox('Panjang (m)',length,(v)=>setState(()=>length=v))),const SizedBox(width:8),Expanded(child:numBox('Lebar (m)',width,(v)=>setState(()=>width=v)))]),const SizedBox(height:10),Row(children:[Expanded(child:numBox('Tinggi dinding',height,(v)=>setState(()=>height=v))),const SizedBox(width:8),Expanded(child:numBox('Overhang',overhang,(v)=>setState(()=>overhang=v)))]),const SizedBox(height:10),DropdownButtonFormField<int>(value:floors,decoration:const InputDecoration(labelText:'Lantai',border:OutlineInputBorder()),items:[1,2,3].map((x)=>DropdownMenuItem(value:x,child:Text('$x lantai'))).toList(),onChanged:(v)=>setState(()=>floors=v??1)),const SizedBox(height:10),Card(child:ListTile(title:const Text('Luas bangunan'),trailing:Text('${(r['geometry']['floorArea'] as num).toStringAsFixed(2)} m²')))]else if(tab==2)...[select('Dinding',wall,['lightbrick','brick','batako'],(v)=>setState(()=>wall=v)),select('Lantai',floor,['tile','granite'],(v)=>setState(()=>floor=v)),select('Atap',roof,['genteng','metal'],(v)=>setState(()=>roof=v)),select('Plafon',ceiling,['gypsum','grc'],(v)=>setState(()=>ceiling=v)),Row(children:[Expanded(child:numBox('Pintu',doors.toDouble(),(v)=>setState(()=>doors=v.round()))),const SizedBox(width:8),Expanded(child:numBox('Jendela',windows.toDouble(),(v)=>setState(()=>windows=v.round())))])]else if(tab==3)...[SummaryTable(summary:s),const SizedBox(height:12),Text('Komponen: ${(r['items'] as List).length} item')]else...[_Maket(r:r,top:top,onTop:()=>setState(()=>top=!top))],const SizedBox(height:20),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[if(tab>0)OutlinedButton(onPressed:()=>setState(()=>tab--),child:const Text('Kembali'))else const SizedBox(),FilledButton(onPressed:(){if(tab<4)setState(()=>tab++);else finish();},child:Text(tab==4?'Simpan Proyek':'Lanjut'))])]);}
}
class SummaryTable extends StatelessWidget{final JsonMap summary;const SummaryTable({super.key,required this.summary});@override Widget build(BuildContext c)=>Column(children:summary.entries.where((e)=>e.value is num).map((e)=>ListTile(title:Text(e.key),trailing:Text(money(e.value as num)))).toList());}
class _Maket extends StatelessWidget{final JsonMap r;final bool top;final VoidCallback onTop;const _Maket({required this.r,required this.top,required this.onTop});@override Widget build(BuildContext c)=>Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('Maket / Denah',style:Theme.of(c).textTheme.titleLarge),Switch(value:top,onChanged:(_)=>onTop())]),InteractiveViewer(minScale:.6,maxScale:3,child:CustomPaint(size:const Size(320,320),painter:HousePainter(r,top))) ]);}
class HousePainter extends CustomPainter{final JsonMap r;final bool top;HousePainter(this.r,this.top);@override void paint(Canvas c,Size s){final p=Paint()..style=PaintingStyle.stroke..strokeWidth=3;final g=JsonMap.from(r['geometry']);final w=(g['width'] as num).toDouble(),l=(g['length'] as num).toDouble();final scale=.7*s.width/(l>w?l:w);final rect=Rect.fromLTWH((s.width-l*scale)/2,(s.height-w*scale)/2,l*scale,w*scale);c.drawRect(rect,p);if(top){final x=rect.left+rect.width*.45;c.drawLine(Offset(x,rect.top),Offset(x,rect.bottom),p);c.drawLine(Offset(rect.left,rect.top+rect.height*.55),Offset(rect.right,rect.top+rect.height*.55),p);}}@override bool shouldRepaint(covariant HousePainter old)=>old.top!=top;}
class ProjectsPage extends StatelessWidget{final List<JsonMap> projects;final void Function(int) onDelete;final VoidCallback onNew;const ProjectsPage({super.key,required this.projects,required this.onDelete,required this.onNew});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('Proyek Saya',style:Theme.of(c).textTheme.headlineSmall),FilledButton.icon(onPressed:onNew,icon:const Icon(Icons.add),label:const Text('Baru'))]),if(projects.isEmpty)const ListTile(title:Text('Belum ada proyek'))else...projects.asMap().entries.map((e)=>Card(child:ListTile(title:Text(e.value['name']??'-'),subtitle:Text('${e.value['area']??0} m² • ${money(e.value['total']??0)}'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>onDelete(e.key))))) ]);}
class MaterialPageX extends StatefulWidget{final List<JsonMap> items;final ValueChanged<List<JsonMap>> onChanged;const MaterialPageX({super.key,required this.items,required this.onChanged});@override State<MaterialPageX> createState()=>_MaterialState();}
class _MaterialState extends State<MaterialPageX>{late List<JsonMap> x;@override void initState(){super.initState();x=List<JsonMap>.from(widget.items);}void add(){final n=TextEditingController(),p=TextEditingController();showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Tambah material'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:n,decoration:const InputDecoration(labelText:'Nama')),TextField(controller:p,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Harga'))]),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Batal')),FilledButton(onPressed:(){setState(()=>x.add({'name':n.text,'unit':'unit','price':double.tryParse(p.text)??0}));widget.onChanged(x);Navigator.pop(context);},child:const Text('Simpan'))]));}@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('Material',style:Theme.of(c).textTheme.headlineSmall),FilledButton.icon(onPressed:add,icon:const Icon(Icons.add),label:const Text('Tambah'))]),...RabEngine.materials.entries.map((e)=>ListTile(title:Text(e.value[0]),subtitle:Text('${e.value[1]} • ${money(e.value[2])}'))),...x.map((e)=>ListTile(title:Text(e['name']??'-'),subtitle:Text(money(e['price']??0))))]);}
class MorePage extends StatelessWidget{final ValueChanged<int> onNav;const MorePage({super.key,required this.onNav});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Text('Fitur Lainnya',style:Theme.of(c).textTheme.headlineSmall),...[(7,'Kalkulator',Icons.calculate),(8,'Kwitansi',Icons.receipt_long),(5,'Laporan',Icons.assessment),(6,'Pengaturan',Icons.settings),(4,'Galeri',Icons.image),(9,'Lisensi',Icons.verified_user)].map((x)=>Card(child:ListTile(leading:Icon(x.$3),title:Text(x.$2),trailing:const Icon(Icons.chevron_right),onTap:()=>onNav(x.$1<9?x.$1:6))))]));}
class ReportPage extends StatelessWidget{final List<JsonMap> projects;final JsonMap profile;const ReportPage({super.key,required this.projects,required this.profile});@override Widget build(BuildContext c){final total=projects.fold<double>(0,(a,p)=>a+((p['total'] as num?)?.toDouble()??0));return ListView(padding:const EdgeInsets.all(16),children:[Text('Laporan',style:Theme.of(c).textTheme.headlineSmall),Text(profile['name']??''),ListTile(title:const Text('Jumlah proyek'),trailing:Text('${projects.length}')),ListTile(title:const Text('Total RAB'),trailing:Text(money(total))),...projects.map((p)=>Card(child:ListTile(title:Text(p['name']??'-'),subtitle:Text('${p['area']??0} m²'),trailing:Text(money(p['total']??0)))))]);}}
class SettingsPage extends StatefulWidget{final JsonMap profile;final ValueChanged<JsonMap> onSave;const SettingsPage({super.key,required this.profile,required this.onSave});@override State<SettingsPage> createState()=>_SettingsState();}
class _SettingsState extends State<SettingsPage>{late TextEditingController n,a,c,l;@override void initState(){super.initState();n=TextEditingController(text:widget.profile['name']);a=TextEditingController(text:widget.profile['address']);c=TextEditingController(text:widget.profile['contact']);l=TextEditingController(text:widget.profile['logo']);}@override void dispose(){n.dispose();a.dispose();c.dispose();l.dispose();super.dispose();}@override Widget build(BuildContext cxt)=>ListView(padding:const EdgeInsets.all(16),children:[Text('Pengaturan',style:Theme.of(cxt).textTheme.headlineSmall),TextField(controller:n,decoration:const InputDecoration(labelText:'Nama CV / usaha',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:l,decoration:const InputDecoration(labelText:'Logo (URL/path)',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:a,decoration:const InputDecoration(labelText:'Alamat',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:c,decoration:const InputDecoration(labelText:'Kontak',border:OutlineInputBorder())),const SizedBox(height:18),FilledButton(onPressed:()=>widget.onSave({'name':n.text,'logo':l.text,'address':a.text,'contact':c.text}),child:const Text('Simpan Identitas')),const SizedBox(height:20),const Card(child:ListTile(leading:Icon(Icons.verified_user),title:Text('Lisensi'),subtitle:Text('Arsitektur lisensi siap dihubungkan ke kunci produk/server.')))]);}
class CalculatorPage extends StatefulWidget{const CalculatorPage({super.key});@override State<CalculatorPage> createState()=>_CalcState();}
class _CalcState extends State<CalculatorPage>{final a=TextEditingController(text:'6'),b=TextEditingController(text:'6'),h=TextEditingController(text:'3');@override void dispose(){a.dispose();b.dispose();h.dispose();super.dispose();}@override Widget build(BuildContext c){final area=(double.tryParse(a.text)??0)*(double.tryParse(b.text)??0),vol=area*(double.tryParse(h.text)??0);return ListView(padding:const EdgeInsets.all(16),children:[Text('Kalkulator',style:Theme.of(c).textTheme.headlineSmall),TextField(controller:a,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Panjang')),TextField(controller:b,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Lebar')),TextField(controller:h,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Tinggi')),const SizedBox(height:15),FilledButton(onPressed:()=>setState((){}),child:const Text('Hitung')),ListTile(title:const Text('Luas'),trailing:Text('${area.toStringAsFixed(2)} m²')),ListTile(title:const Text('Volume'),trailing:Text('${vol.toStringAsFixed(2)} m³'))]);}}
class ReceiptPage extends StatefulWidget{const ReceiptPage({super.key});@override State<ReceiptPage> createState()=>_ReceiptState();}
class _ReceiptState extends State<ReceiptPage>{final no=TextEditingController(text:'KWT-001'),name=TextEditingController(),amount=TextEditingController();@override void dispose(){no.dispose();name.dispose();amount.dispose();super.dispose();}@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[Text('Kwitansi',style:Theme.of(c).textTheme.headlineSmall),TextField(controller:no,decoration:const InputDecoration(labelText:'Nomor')),TextField(controller:name,decoration:const InputDecoration(labelText:'Diterima dari')),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Jumlah')),const SizedBox(height:15),FilledButton(onPressed:()=>setState((){}),child:const Text('Pratinjau')),Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[const Text('KWITANSI PEMBAYARAN'),Text(no.text),Text(name.text),Text(money(double.tryParse(amount.text)??0))])))]);}
