name: rab_rumahku
description: RAB Rumahku Pro - perencanaan rumah, quantity takeoff, material, RAB dan maket 3D
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.4.0
  path_provider: ^2.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
