name: rab_rumahku
description: RAB Rumahku offline-first mobile client
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.4.0
  path_provider: ^2.1.5
  intl: ^0.20.2
flutter:
  uses-material-design: true
